[pytest]
; markers ANDREI:in the future

; Configuración para que encuentre los tests en index.py
python_files = index.py

; opciones adicionales

; --tracing=on pa ver logs xd 
addopts = --base-url https://www.google.com --headed --slowmo 1000 --screenshot=only-on-failure